---

- name: Install logstash public sign key
  rpm_key: key=https://artifacts.elastic.co/GPG-KEY-elasticsearch state=present

- name: Install logstash 5.x repo
  copy: src=logstash.repo dest=/etc/yum.repos.d/logstash.repo owner=root mode=644

- name: Install logstash 5.x
  yum: name=logstash state=latest
  notify: restart logstash

- name: Enable logstash service
  service: name=logstash enabled=yes



